luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<email>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

realty/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailRealtyView.as_view(), name='details'),
    url(r'^add/', views.AddRealtyView.as_view(), name="add-realty"),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
]

vehicles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add/', views.AddCarView.as_view(), name="add-vehicle"),
    url(r'^search/', views.MainCarView.as_view(), name="search"),
    url(r'^details/(?P<pk>[0-9]+)/$', views.DetailCarView.as_view(), name='car-details'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^search/autocomplete/', views.autocomplete, name='autocomplete'),
    url(r'^postadd/$', views.AddCarView.as_view(), name="AddCar"),
    url(r'^get_models/', views.get_models, name='get_models'),
    url(r'^get_colors/', views.get_colors, name='get_colors'),
    url(r'^get_brands/', views.get_brands, name='get_brands'),
]

vehicles/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import datetime, json, random, re
import hashlib

from django.contrib.gis.geos import Point
from django.contrib.postgres.fields import ArrayField
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _

YEAR_CHOICES = [(r, r) for r in range(1886, (datetime.datetime.now().year + 1))]
MONTH_CHOICES = [(r, r) for r in range(1, 13)]
YEARMONTH_INPUT_FORMATS = (
    '%m-%Y', '%m/%Y', '%m/%y',  # '2006-10', '10/2006', '10/06'
)


# sssssssssssss >
# class YearMonthField(models.CharField):
#     default_error_messages = {
#         'invalid': _('Enter a valid year and month.'),
#     }

#     def __init__(self, input_formats=None, *args, **kwargs):
#         super(YearMonthField, self).__init__(*args, **kwargs)
#         self.input_formats = input_formats

#     def clean(self, value):
#         if value in validators.EMPTY_VALUES:
#             return None
#         if isinstance(value, datetime.datetime):
#             return format(value, '%Y-%m')
#         if isinstance(value, datetime.date):
#             return format(value, '%Y-%m')
#         for fmt in self.input_formats or YEARMONTH_INPUT_FORMATS:
#             try:
#                 date = datetime.date(*datetime.time.strptime(value, fmt)[:3])
#                 return format(date, '%Y-%m')
#             except ValueError:
#                 continue
#         raise ValidationError(self.error_messages['invalid'])
# sssssssssss <


class Manufacturer(models.Model):
    manufacturer_code = models.CharField(max_length=50, null=True, verbose_name=_('Manufacturer Code'))
    manufacturer_name = models.CharField(max_length=50, null=True, verbose_name=_('Manufacturer Name'))
    manufacturer_details = models.TextField(null=True, verbose_name=_('Manufacturer Detials'))

    def __unicode__(self):
        return "%s %s %s" % (self.manufacturer_code, self.manufacturer_name, self.manufacturer_details)


class Brand(models.Model):
    # Vehicle = models.ForeignKey(Vehicle)
    brand_code = models.CharField(max_length=30, blank=True, null=True, verbose_name=_('Brand Code'))
    brand_name = models.CharField(max_length=50, blank=True, null=True, verbose_name=_('Brand Name'))

    def __unicode__(self):
        return self.brand_name


class Model(models.Model):
    brand = models.ForeignKey(Brand)
    model_code = models.CharField(max_length=50, verbose_name=_('Model Code'))
    model_name = models.CharField(max_length=50, verbose_name=_('Model Name'))

    def __unicode__(self):
        return unicode(self.model_name)


SELLER_CHOICES = ((1, _('Private seller')),
                  (2, _('Professional  seller')))


class Seller(models.Model):
    name = models.CharField(_('Seller'), max_length=100, null=True)
    phones = models.CharField(_('Phone'), max_length=100, null=True)
    location = models.CharField(_('Address'), max_length=100, null=True)
    seller_type = models.PositiveIntegerField(_('Seller type'), choices=SELLER_CHOICES, default=1)

    def __unicode__(self):
        return unicode(self.seller)


class Country(models.Model):
    name = models.CharField(_('Country'), max_length=50)

    def __unicode__(self):
        return self.name


class BaseColor(models.Model):
    color = models.CharField(max_length=50)


class Color(models.Model):
    color = models.CharField(max_length=50)
    base_color = models.ForeignKey(BaseColor, null=True, blank=True, related_name='uscolor')

    def __unicode__(self):
        return self.color


class Car(models.Model):
    VEHICLE_CHOICES = (
        (1, _('Car')),
        (2, _('MotorCycle')),
        (3, _('Utility'))
    )

    country = models.ForeignKey(Country, null=True, blank=True)
    vehicle_type = models.PositiveIntegerField(choices=VEHICLE_CHOICES, default=1)
    brand = models.ForeignKey(Brand, null=True)
    model = models.ForeignKey(Model, null=True)
    finition = models.CharField(_('Finition'), max_length=50, null=True, blank=True)
    model_type = models.CharField(_('Model type'), max_length=100, null=True, blank=True)
    model_month = models.IntegerField(_('Model Month'), choices=MONTH_CHOICES, null=True, blank=True)
    model_year = models.IntegerField(_('Model year'), choices=YEAR_CHOICES, null=True, blank=True)
    seller = models.ForeignKey(Seller, null=True)
    km = models.PositiveIntegerField(_('Mileage'), null=True, blank=True)
    price = models.PositiveIntegerField(_('Price'), null=True, blank=True)
    energy = models.CharField(_('Fuel'), max_length=50, blank=True)
    gear_box = models.CharField(_('Gear Box'), max_length=50, blank=True)
    cylinder = models.CharField(_('Cylinder volume'), max_length=50, null=True, blank=True)
    power = models.CharField(_('Power'), max_length=50, null=True, blank=True)
    color = models.ForeignKey(Color, null=True, blank=True)
    color_inside = models.ForeignKey(Color, null=True, related_name='car_inside', blank=True)
    doors = models.PositiveIntegerField(_('Doors'), null=True, blank=True)
    url = models.URLField("URL", null=True, blank=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    creation_date = models.DateTimeField(default=timezone.now)
    places = models.PositiveIntegerField(blank=True, null=True)
    weight = models.PositiveIntegerField(blank=True, null=True)
    price_history = ArrayField(models.IntegerField(), blank=True, null=True)
    options = models.TextField(blank=True)
    description = models.TextField(blank=True)

    def get_options(self):
        return json.loads(self.options)

    def phones_as_list(self):
        return self.seller.phones.split(',')

    def __unicode__(self):
        return unicode(self.brand.brand_name)

    def get_location(self):
        if self.longitude and self.latitude:
            return Point(self.longitude, self.latitude)
        else:
            return None

    def update_price(self, new_price):
        if self.price != new_price:
            if self.price_history:
                index = len(self.price_history) - 1
                if self.price and self.price != self.price_history[index]:
                    self.price_history.append(self.price)
                elif new_price == self.price_history[index]:
                    del self.price_history[index]
            elif self.price:
                self.price_history = [self.price]
            self.price = new_price
            self.save()

    @property
    def domain(self):
        if self.url:
            domain = re.search(r'\/\/([^\/]+)', self.url)
            if domain:
                return domain.groups()[0]
        return ''


def get_hash_name(brand, model, filename):
    ext = filename.split('.')[-1]
    hash_object = hashlib.md5(
        str(brand).decode('utf-8').encode('utf-8') + str(model).encode() + str(datetime.datetime.now()).encode())
    return '{}.{}'.format(hash_object.hexdigest(), ext)


def img_upload_to(instance, filename):
    return 'car-us/%s/%s/%s' % (
        datetime.datetime.now().year, instance.car_id, get_hash_name(instance.car.brand, instance.car.model, filename))


class CarImage(models.Model):
    car = models.ForeignKey(Car)
    image = models.ImageField(upload_to=img_upload_to, blank=False)

luxdjango/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import json, re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext as _
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View

#from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import LoginRequiredMixin
from .models import User, Subscription
from vehicles.models import Country
from realty.models import PropertyType, PropertyTypeType, City


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        subscriptions = self.request.user.subscription_set.all()
        result = {}

        for s in subscriptions:
            raw_filters = json.loads(s.filters)
            filters = {}

            if 'property_type_type' in raw_filters:
                filters['Property type'] = PropertyTypeType.objects.filter(
                    id=raw_filters['property_type_type']
                ).first().name
            elif 'property_type' in raw_filters:
                filters['Property type'] = PropertyType.objects.filter(
                    id=raw_filters['property_type']
                ).first().name
            if 'city' in raw_filters:
                filters['City'] = City.objects.get(id=raw_filters['city'])
            if 'deal' in raw_filters:
                filters[_('Deal')] = _('Sale') if raw_filters['deal'] == 1 else _('Rent')

            for key in raw_filters:
                key2 = None
                if key.endswith('_index'):
                    key2 = key.replace('_index', '')
                elif key == 'q' and raw_filters[key]:
                    key2 = 'text'
                elif key == 'countries' and raw_filters[key]:
                    key2 = key
                    country_ids = [int(x) for x in raw_filters[key].split(',')]
                    country_names = Country.objects.filter(
                        id__in=country_ids
                    ).values_list('name', flat=True)
                    raw_filters[key] = ', '.join(country_names)
                elif key == 'distance':
                    # user location should be in user model to filter search by distance
                    continue
                elif key in ['price_index', 'year_index', 'mileage_index', 'year_index']:
                    key2 = key
                    raw_filters[key] = raw_filters[key].replace(',', ' - ')

                if key2:
                    key2 = key2.replace('_', ' ').capitalize()
                    filters[key2] = raw_filters[key]
                    if key2 not in ['Brand', 'Countries']:
                        filters[key2] = filters[key2].lower()



            if not filters:
                filters['Without filters'] = 'any updates'
            result[s.id] = filters

        context['subscriptions'] = result
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['email', ]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(email=self.request.user.email)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"


class Subscribe(View):

    def post(self, request):
        category = re.match(r'^[^\/]+\/\/[^\/]+\/(\w+)', request.META['HTTP_REFERER']).groups()[0]
        if category == 'vehicles':
            category = 1
        elif category == 'realty':
            category = 2
        if request.user.is_authenticated():
            data = json.loads(request.POST['filters'])
            if 'page' in data:
                del data['page']
            if 'scroll' in data:
                del data['scroll']
            for key in ['year_index', 'mileage_index']:
                if key in data:
                    data[key] = data[key].replace('.00', '')
            Subscription.objects.get_or_create(filters=json.dumps(data),
                                               user=request.user,
                                               category=category)
            return HttpResponse(status=204)
        else:
            return HttpResponse('Not authenticated!', status=400)


class DeleteSubscriptions(LoginRequiredMixin, View):

    def post(self, request):
        ids = json.loads(request.POST['subscriptions'])
        request.user.subscription_set.filter(id__in=ids).delete()
        return HttpResponse(status=204)


def social_redirect(request):
    next_url = request.GET.get('url', ).replace('|', '?').replace('^', '&')
    if next_url:
        return redirect(to=next_url)
    return redirect(to=settings.LOGIN_REDIRECT_URL)

luxdjango/templates/search/car_item_preview.html
{% load pagination_tags staticfiles thumbnail %}
{% autopaginate object_list 10 %}
{% for result in object_list %}
    {% with i=result.object %}
        <div class="row c-margin-b-40">
            <div class="c-content-product-2 c-bg-white">
                <div class="col-md-4">
                    <div class="c-content-overlay">
                        <div class="c-overlay-wrapper">
                            <div class="c-overlay-content">
                                <a href="{% url "vehicles:car-details" i.id %}" class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square">Explore</a>
                            </div>
                        </div>
                        {% thumbnail i.carimage_set.first.image "260x230" crop="center" as im %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 230px; background-image: url({{ im.url }});"></div>
                        {% empty %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height" style="height: 230px; background-image: url({% static "assets/base/img/cars/sport-car.svg"%});"></div>
                        {% endthumbnail %}
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="c-info-list">
                        <h3 class="c-title c-font-bold c-font-22 c-font-dark">
                            <a class="c-theme-link" href="{% url "vehicles:car-details" i.id %}">{{ i.brand.brand_name }} {{ i.model.model_name }}</a>
                        </h3>
                        {% if i.gear_box %}
                            <p class="c-desc c-font-16 c-font-thin"> gear box - {{ i.gear_box }}</p>
                        {% endif %}
                        {% if i.color.color %}
                            <p class="c-desc c-font-16 c-font-thin"> color - {{ i.color.color }}<span style="background: {{ i.color }}" class="color_faced_box" title="{{ i.color }}"></span></p>
                        {% endif %}
                        {% if i.model_year %}
                            <p class="c-desc c-font-16 c-font-thin"> year - {{ i.model_year }}</p>
                        {% endif %}
                        {% if i.km %}
                            <p class="c-desc c-font-16 c-font-thin"> mileage - {{ i.km }} </p>
                        {% endif %}
                        {% if i.country.name %}
                            <p class="c-desc c-font-16 c-font-thin"> country - {{ i.country.name }} </p>
                        {% endif %}
                        {% if i.price %}
                            <p class="c-price c-font-26 c-font-thin">{{ i.price }} &#8364;
                                {% for p in i.price_history %}
                                    <span class="c-font-26 c-font-line-through c-font-red">{{ p }} &#8364;</span>
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
{% empty %}<p>No results found.</p>{% endfor %}
{#{% paginate %}#}

luxdjango/templates/search/colors_filter.html
<h3 class="c-font-uppercase c-font-bold">Colors</h3>
<div class="c-line-left"></div>
{% for c in colors %}
    <div style="background: {{ c.0 }}" class="color_faced_box" title="{{ c.1 }}" data_info="{{ c.0 }}"></div>
{% endfor %}

luxdjango/templates/search/left_sidebar_filters.html
{% load common %}
{% load staticfiles i18n %}

<form name="search_form">
    {% for index, values in facets.items %}
        {% if values %}
            <li>
                <label class="control-label c-font-uppercase c-font-bold">{% trans index %}</label>
                <div style="{% if values|length >= 9 %}overflow: scroll;{% endif %} max-height: 340px; overflow-x: hidden;">
                    {% for k, c in values %}
                        <div class="c-checkbox">
                            <input type="checkbox" id="{{ index }}{{ forloop.counter }}" class="c-check"
                                   name="{{ index }}"
                                   value="{% if k %}{{ k }}{% else %}not_provided{% endif %}"
                                    {% if conditions|key:index == k or conditions|key:index == "not_provided" %}
                                   checked {% endif %}>
                            <label for="{{ index }}{{ forloop.counter }}">
                                <span class="inc"></span>
                                <span class="check"></span>
                                <span class="box"></span>
                                <p>{% if k %}{{ k | slice:"14" }}{% else %}Not provided{% endif %} - {{ c }}</p>
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </li>
        {% endif %}
    {% endfor %}
</form>

luxdjango/templates/search/search_wrapper.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'assets/plugins/select2-4.0.3/select2.min.css' %}">
    <link href={% static "assets/plugins/rangeslider/nouislider.min.css" %} rel="stylesheet">
{% endblock extra_css %}

{% block content %}
    <!-- BEGIN: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
    <div class="c-layout-breadcrumbs-1 c-subtitle c-fonts-uppercase c-fonts-bold c-bordered c-bordered-both">
        <div class="container">
            <ul class="c-page-breadcrumbs c-theme-nav c-pull-right c-fonts-regular">
                <li class="chosen-wrapper">
                    <select data-placeholder="{% trans "Choose a country" %}..."
                            multiple class="chosen-select-country" class="search-filter">
                        {% for c in list_of_country %}
                            <option name="countries" value="{{ c.id }}" >{{ c.name }}</option>
                        {% endfor %}
                    </select>
                </li>
                <li class="your-loc">{% trans "Your location" %}:
                    <span id="locate-me"><a href="#">{% trans "locate me" %}</a></span>
                </li>
                <li class="your-loc" id="your-location"></li>
                <li></li>
                <li><div style="width: 250px;" id="radius-rangefilter"></div></li>
                <li><div style="margin-left: 10px;"  id="radius-step-value"></div></li>
            </ul>
        </div>
    </div>
    <!-- END: LAYOUT/BREADCRUMBS/BREADCRUMBS-2 -->
    <div class="container">
        <div class="c-layout-sidebar-menu c-theme">
            <!-- BEGIN: LAYOUT/SIDEBARS/SHOP-SIDEBAR-MENU -->


            <div class="c-sidebar-menu-toggler">
                <h3 class="c-title c-font-uppercase c-font-bold">{% trans "Filters" %}</h3>
                <a href="javascript:;" class="c-content-toggler" data-toggle="collapse" data-target="#sidebar-menu-2">
                    <span class="c-line"></span>
                    <span class="c-line"></span>
                    <span class="c-line"></span>
                </a>
            </div>

            <div class="c-sidebar-menu collapse" id="sidebar-menu-2">
            <div id="left-sidebar-filters" class="fire-reload-filters c-shop-filter-search-1 list-unstyled">
            </div>
                <div class="c-padding-20 c-margin-t-40 c-bg-grey-1 c-bg-img-bottom-right">
                    <div class="c-content-title-1 c-margin-t-20">
                        <h3 class="c-font-uppercase c-font-bold">{% trans "Price" %}</h3>
                        <div class="c-line-left"></div>
                        <div id="price_index-range_slider" ></div>
                        <input class="input-number" id="price_index-input-number-r">
                        <input class="input-number" id="price_index-input-number-l">
                    </div>
                </div>
                {% block sidebar_range_filters %} {% endblock sidebar_range_filters %}
            </div>
            <!-- END: LAYOUT/SIDEBARS/SHOP-SIDEBAR-MENU -->
        </div>

        <div class="c-layout-sidebar-content ">
            <!-- BEGIN: PAGE CONTENT -->
            <!-- BEGIN: CONTENT/SHOPS/SHOP-RESULT-FILTER-1 -->
            <div class="c-shop-result-filter-1 clearfix form-inline" id="sort">
                    <div class="c-filter">
                        <label class="control-label c-font-16">Sort&nbsp;By:</label>
                        <select id="sort" class="form-control c-square c-theme c-input">
                            <option value="-year_index">{% trans "Year built" %} ({% trans "New" %} > {% trans "Old" %})</option>
                            <option value="year_index" selected>{% trans "Year built" %} ({% trans "Old" %}>{% trans "New" %})</option>
                            <option value="price_index">{% trans "Price" %} ({% trans "Low" %} &gt; {% trans "High" %})</option>
                            <option value="-price_index" selected>{% trans "Price" %} ({% trans "High" %} &gt; {% trans "Low" %})</option>
                            <option value="-date_index">{% trans "Date" %} ({% trans "New" %} &gt; {% trans "Old" %})</option>
                            <option value="date_index" selected>{% trans "Date" %} ({% trans "Old" %} &gt; {% trans "New" %})</option>
                            <option value="" selected="selected">Default</option>
                        </select>
                    </div>
            </div>
            <!-- END: CONTENT/SHOPS/SHOP-RESULT-FILTER-1 -->
            <div class="c-margin-t-20"></div>
            <span id="search-list-result"  class="fire-reload-pagination"></span>
            <div class="c-margin-t-20"></div>
        </div>
    </div>
<!-- END: PAGE CONTAINER -->
{% endblock content %}
{% block extra_js %}
    <script src="{% static 'assets/plugins/rangeslider/nouislider.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/select2-4.0.3/select2.min.js' %}"></script>
    <script src="{% static 'assets/base/js/modules/search-page.js' %}" type="text/javascript"></script>
{% endblock extra_js %}

luxdjango/templates/search/vehicle_search.html
{% extends "search/search_wrapper.html" %}
{% load i18n %}

{% block sidebar_range_filters %}
    <div class="c-padding-20 c-margin-t-40 c-bg-grey-1 c-bg-img-bottom-right">
        <div class="c-content-title-1 c-margin-t-20">
            <h3 class="c-font-uppercase c-font-bold">{% trans "Years" %}</h3>
            <div class="c-line-left"></div>
            <div id="year_index-range_slider" ></div>
            <input class="input-number" id="year_index-input-number-r">
            <input class="input-number" id="year_index-input-number-l">
        </div>
    </div>
    <div class="c-padding-20 c-margin-t-40 c-bg-grey-1 c-bg-img-bottom-right">
        <div class="c-content-title-1 c-margin-t-20" id="colors-filters">
        </div>
    </div>
    <div class="c-padding-20 c-margin-t-40 c-bg-grey-1 c-bg-img-bottom-right" >
        <div class="c-content-title-1 c-margin-t-20">
            <h3 class="c-font-uppercase c-font-bold">{% trans "Mileage" %}</h3>
            <div class="c-line-left"></div>
            <div id="mileage_index-range_slider" ></div>
            <input class="input-number" id="mileage_index-input-number-r">
            <input class="input-number" id="mileage_index-input-number-l">
        </div>
    </div>
{% endblock sidebar_range_filters %}

{% block extra_js %}
    {{ block.super }}
    <script>
        djangoContext.urls.ajaxSearch = "{% url 'vehicles:search-ajax' %}"

        document.addEventListener('DOMContentLoaded', function () {
            SearchPage({
                q_text: "{{ request.GET.q }}",
                url:"don't forget forward url namespace",
                rangeFiltersList: {
                    'price_index': [1, 300000],
                    'year_index': [1940, new Date().getFullYear()],
                    'mileage_index': [1, 200000]
                }
            });
        });
    </script>
{% endblock extra_js %}