luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<email>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

realty/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailRealtyView.as_view(), name='details'),
    url(r'^add/', views.AddRealtyView.as_view(), name="add-realty"),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
]

vehicles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add/', views.AddCarView.as_view(), name="add-vehicle"),
    url(r'^search/', views.MainCarView.as_view(), name="search"),
    url(r'^details/(?P<pk>[0-9]+)/$', views.DetailCarView.as_view(), name='car-details'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^search/autocomplete/', views.autocomplete, name='autocomplete'),
    url(r'^postadd/$', views.AddCarView.as_view(), name="AddCar"),
    url(r'^get_models/', views.get_models, name='get_models'),
    url(r'^get_colors/', views.get_colors, name='get_colors'),
    url(r'^get_brands/', views.get_brands, name='get_brands'),
]

luxdjango/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from luxdjango.users.managers import UserManager
from vehicles.models import Country


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    country = models.ForeignKey(Country, null=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Subscription(models.Model):
    CATEGORY_CHOICES = ((1, 'vehicles'), (2, 'realty'))
    user = models.ForeignKey(User)
    filters = models.CharField(max_length=500)
    last_notification = models.DateTimeField(null=True, blank=True)
    category = models.PositiveIntegerField(choices=CATEGORY_CHOICES)

luxdjango/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import json, re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext as _
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View

#from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import LoginRequiredMixin
from .models import User, Subscription
from vehicles.models import Country
from realty.models import PropertyType, PropertyTypeType, City


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        subscriptions = self.request.user.subscription_set.all()
        result = {}

        for s in subscriptions:
            raw_filters = json.loads(s.filters)
            filters = {}

            if 'property_type_type' in raw_filters:
                filters['Property type'] = PropertyTypeType.objects.filter(
                    id=raw_filters['property_type_type']
                ).first().name
            elif 'property_type' in raw_filters:
                filters['Property type'] = PropertyType.objects.filter(
                    id=raw_filters['property_type']
                ).first().name
            if 'city' in raw_filters:
                filters['City'] = City.objects.get(id=raw_filters['city'])
            if 'deal' in raw_filters:
                filters[_('Deal')] = _('Sale') if raw_filters['deal'] == 1 else _('Rent')

            for key in raw_filters:
                key2 = None
                if key.endswith('_index'):
                    key2 = key.replace('_index', '')
                elif key == 'q' and raw_filters[key]:
                    key2 = 'text'
                elif key == 'countries' and raw_filters[key]:
                    key2 = key
                    country_ids = [int(x) for x in raw_filters[key].split(',')]
                    country_names = Country.objects.filter(
                        id__in=country_ids
                    ).values_list('name', flat=True)
                    raw_filters[key] = ', '.join(country_names)
                elif key == 'distance':
                    # user location should be in user model to filter search by distance
                    continue
                elif key in ['price_index', 'year_index', 'mileage_index', 'year_index']:
                    key2 = key
                    raw_filters[key] = raw_filters[key].replace(',', ' - ')

                if key2:
                    key2 = key2.replace('_', ' ').capitalize()
                    filters[key2] = raw_filters[key]
                    if key2 not in ['Brand', 'Countries']:
                        filters[key2] = filters[key2].lower()



            if not filters:
                filters['Without filters'] = 'any updates'
            result[s.id] = filters

        context['subscriptions'] = result
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['email', ]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(email=self.request.user.email)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"


class Subscribe(View):

    def post(self, request):
        category = re.match(r'^[^\/]+\/\/[^\/]+\/(\w+)', request.META['HTTP_REFERER']).groups()[0]
        if category == 'vehicles':
            category = 1
        elif category == 'realty':
            category = 2
        if request.user.is_authenticated():
            data = json.loads(request.POST['filters'])
            if 'page' in data:
                del data['page']
            if 'scroll' in data:
                del data['scroll']
            for key in ['year_index', 'mileage_index']:
                if key in data:
                    data[key] = data[key].replace('.00', '')
            Subscription.objects.get_or_create(filters=json.dumps(data),
                                               user=request.user,
                                               category=category)
            return HttpResponse(status=204)
        else:
            return HttpResponse('Not authenticated!', status=400)


class DeleteSubscriptions(LoginRequiredMixin, View):

    def post(self, request):
        ids = json.loads(request.POST['subscriptions'])
        request.user.subscription_set.filter(id__in=ids).delete()
        return HttpResponse(status=204)


def social_redirect(request):
    next_url = request.GET.get('url', ).replace('|', '?').replace('^', '&')
    if next_url:
        return redirect(to=next_url)
    return redirect(to=settings.LOGIN_REDIRECT_URL)

luxdjango/templates/headers/base_header.html
{% load i18n staticfiles customtags %}
<!-- BEGIN: LAYOUT/HEADERS/HEADER-2 -->
<!-- BEGIN: HEADER 2 -->
<header class="c-layout-header c-layout-header-6 c-navbar-fluid" data-minimize-offset="80">
    <div class="c-topbar">
        <div class="container">
            <div class="c-brand">
                <a href="/" class="c-logo">
                    <img src="{% static "assets/base/img/skruut.jpg" %}" alt="JANGO" class="c-desktop-logo" style="height: 60px">
                    <img src="{% static "assets/base/img/skruut.jpg" %}" alt="JANGO" class="c-desktop-logo-inverse">
                    <img src="{% static "assets/base/img/skruut.jpg" %}" alt="JANGO" class="c-mobile-logo">
                    <a class="c-font-uppercase c-font-bold" style="font-size: 30px;color: #7a7a7a">SKRUUT</a>
                </a>
            </div>
            <nav class="c-top-menu">
                <ul class="c-links c-theme-ul">
                    <li><a class="c-font-uppercase c-font-bold" href="{% url 'vehicles:search' %}">vehicles</a></li>
                    <li><a class="c-font-uppercase c-font-bold" href="{% url 'realty:search' %}">realty</a></li>
                    <li><a class="c-font-uppercase c-font-bold" href="/">jobs</a></li>
                    <li class="c-divider"></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url "users:detail" request.user.email %}" class="c-font-uppercase c-font-bold">My profile</a></li>
                    {% endif %}
                    <li>
                        {% get_url_first_arg as URL_FIRST_ARG %}
                        <a id="add_post" class="c-font-uppercase c-font-bold c-font-dark"
                            {% if URL_FIRST_ARG == 'vehicles' %}
                                href="{% url 'vehicles:add-vehicle' %}"
                            {% elif URL_FIRST_ARG == 'realty' %}
                                href="{% url 'realty:add-realty' %}"
                            {% else %}
                               data-toggle="modal" data-target="#choose-category"
                            {% endif %}>
                            <span class="glyphicon glyphicon-plus"></span> {% trans "Post Add" %}
                        </a>
                    </li>
                    <li>
                        {% if request.user.is_authenticated %}
                            <a id="sign-out" href="{% url "account_logout" %}" data-toggle="modal" data-target="#login-form"
                               class="btn c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'Sign out' %}</a>
                        {% else %}
                            <a id="sign-in" href="javascript:;" data-toggle="modal" data-target="#login-form"
                               class="btn c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'Sign In' %}</a>
                        {% endif %}
                    </li>
                </ul>
                <form id="lang-form" class="hidden" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="language">
                </form>
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <ul class="c-ext c-theme-ul">
                    <li class="c-lang dropdown c-last">
                        <a id="current-lang" href="#">{{ LANGUAGE_CODE }}</a>
                        <ul class="dropdown-menu pull-right" role="menu">
                            {% for language in languages %}
                                {% if language.code != LANGUAGE_CODE %}
                                    <li class="change-lang" data-lang-code={{ language.code }}>
                                        <a href="#">{{ language.name_local }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="c-navbar">
        <div class="container">
            <div class="c-navbar-wrapper clearfix">
                <form class="c-quick-search" action="{% url 'vehicles:search' %}" name="search_form">
                    <input type="text" name="q" placeholder="{% trans "Type to search" %}..." value=""
                           class="form-control fire-reload" autocomplete="off">
                </form>
                {% if '/search/' in request.path %}
                    <a id="subscribe-btn" href="javascript:;"
                       class="btn c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans "subscribe to the notification" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>
<!-- END: HEADER 2 -->
<!-- END: LAYOUT/HEADERS/HEADER-2 -->

<!-- BEGIN: CONTENT/USER/FORGET-PASSWORD-FORM -->
<div class="modal fade c-content-login-form" id="forget-password-form" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content c-square">
            <div class="modal-header c-no-border">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3 class="c-font-24 c-font-sbold">{% trans "Password Recovery" %}</h3>
                <p>{% trans "To recover your password please fill in your email address" %}</p>
                <form>
                    <div class="form-group">
                        <label for="forget-email" class="hide">{% trans "Email" %}</label>
                        <input type="email" class="form-control input-lg c-square" id="forget-email"
                               placeholder="Email"></div>
                    <div class="form-group">
                        <button class="btn c-theme-btn btn-md c-btn-uppercase c-btn-bold c-btn-square c-btn-login"
                                type="submit">{% trans "Submit" %}</button>
                        <a href="javascript:;" class="c-btn-forgot" data-toggle="modal" data-target="#login-form"
                           data-dismiss="modal">{% trans "Back To Login" %}</a>
                    </div>
                </form>
            </div>
            <div class="modal-footer c-no-border">
                <span class="c-text-account">{% trans "Don't Have An Account Yet ?" %}</span>
                <a class="btn c-btn-dark-1 btn c-btn-uppercase c-btn-bold c-btn-slim c-btn-border-2x c-btn-square c-btn-signup"
                   href="javascript:;" data-toggle="modal" data-target="#signup-form"
                   data-dismiss="modal">{% trans "Signup" %}!</a>

            </div>
        </div>
    </div>
</div>
<!-- END: CONTENT/USER/FORGET-PASSWORD-FORM -->

{% include "account/modal_signup.html" %}
{% include "account/modal_login.html" %}

<div class="modal fade" id="choose-category" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-plus"></span> POST ADD</h4>
            </div>
            <div class="modal-body">
                <div>
                    <a href="{% url 'vehicles:add-vehicle' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">ADD VEHICLE</a>
                    <br>
                    <a href="{% url 'realty:add-realty' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">ADD REALTY</a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn c-theme-btn c-btn-square c-btn-uppercase c-btn-bold"
                        data-dismiss="modal">Close
                </button>
            </div>
        </div>
    </div>
</div>

luxdjango/templates/headers/base_header2.html
{% load staticfiles %}
<header class="c-layout-header c-layout-header-4 c-layout-header-default-mobile" data-minimize-offset="80">
    <div class="c-navbar">
        <div class="container">
            <div class="c-navbar-wrapper clearfix">
                <!-- BEGIN: BRAND -->
                <div class="c-brand c-pull-left" style="margin:20px 10px">
                    <a href="/" class="c-logo" style="font-weight:bold; color:#7a7a7a; font-size: 30px; display:inline-block">
                        <img src="{% static 'assets/base/img/skruut60.jpg' %}" alt="JANGO" class="c-desktop-logo">
                        <img src="{% static 'assets/base/img/skruut40.jpg' %}" alt="JANGO" class="c-desktop-logo-inverse">
                        <img src="{% static 'assets/base/img/skruut40.jpg' %}" alt="JANGO" class="c-mobile-logo">
                        <span>SKRUUT</span>
                    </a>
                    <button class="c-hor-nav-toggler" type="button" data-target=".c-mega-menu">
                        <span class="c-line"></span>
                        <span class="c-line"></span>
                        <span class="c-line"></span>
                    </button>
                    <button class="c-search-toggler" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
                <!-- END: BRAND -->
                <!-- BEGIN: QUICK SEARCH -->
                <form class="c-quick-search" action="#">
                    <input type="text" name="query" placeholder="Type to search..." value="" class="form-control" autocomplete="off">
                    <span class="c-theme-link">&times;</span>
                </form>
                <!-- END: QUICK SEARCH -->
                <!-- BEGIN: HOR NAV -->
                <!-- BEGIN: MEGA MENU -->
                <!-- Dropdown menu toggle on mobile: c-toggler class can be applied to the link arrow or link itself depending on toggle mode -->
                <nav class="c-mega-menu c-pull-right c-mega-menu-dark c-mega-menu-dark-mobile c-fonts-uppercase c-fonts-bold">
                    <ul class="nav navbar-nav c-theme-nav">
                        <li><a href="{% url 'vehicles:search' %}" class="c-link">vehicles</a></li>
                        <li class="c-active c-menu-type-classic"><a href="{% url 'realty:search' %}" class="c-link">realty</a></li>
                        <li class="c-search-toggler-wrapper">
                            <a href="#" class="c-btn-icon c-search-toggler">
                                <i class="fa fa-search"></i>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" data-toggle="modal" data-target="#login-form"
                                class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-dark c-btn-circle c-btn-uppercase c-btn-sbold">
                                <i class="icon-user"></i> Sign In</a>
                        </li>
                    </ul>
                </nav>
                <!-- END: MEGA MENU -->
                <!-- END: HOR NAV -->
            </div>
        </div>
    </div>
</header>