luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<email>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

realty/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailRealtyView.as_view(), name='details'),
    url(r'^add/', views.AddRealtyView.as_view(), name="add-realty"),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
]

luxdjango/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from luxdjango.users.managers import UserManager
from vehicles.models import Country


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    country = models.ForeignKey(Country, null=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Subscription(models.Model):
    CATEGORY_CHOICES = ((1, 'vehicles'), (2, 'realty'))
    user = models.ForeignKey(User)
    filters = models.CharField(max_length=500)
    last_notification = models.DateTimeField(null=True, blank=True)
    category = models.PositiveIntegerField(choices=CATEGORY_CHOICES)

luxdjango/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import json, re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext as _
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View

#from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import LoginRequiredMixin
from .models import User, Subscription
from vehicles.models import Country
from realty.models import PropertyType, PropertyTypeType, City


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        subscriptions = self.request.user.subscription_set.all()
        result = {}

        for s in subscriptions:
            raw_filters = json.loads(s.filters)
            filters = {}

            if 'property_type_type' in raw_filters:
                filters['Property type'] = PropertyTypeType.objects.filter(
                    id=raw_filters['property_type_type']
                ).first().name
            elif 'property_type' in raw_filters:
                filters['Property type'] = PropertyType.objects.filter(
                    id=raw_filters['property_type']
                ).first().name
            if 'city' in raw_filters:
                filters['City'] = City.objects.get(id=raw_filters['city'])
            if 'deal' in raw_filters:
                filters[_('Deal')] = _('Sale') if raw_filters['deal'] == 1 else _('Rent')

            for key in raw_filters:
                key2 = None
                if key.endswith('_index'):
                    key2 = key.replace('_index', '')
                elif key == 'q' and raw_filters[key]:
                    key2 = 'text'
                elif key == 'countries' and raw_filters[key]:
                    key2 = key
                    country_ids = [int(x) for x in raw_filters[key].split(',')]
                    country_names = Country.objects.filter(
                        id__in=country_ids
                    ).values_list('name', flat=True)
                    raw_filters[key] = ', '.join(country_names)
                elif key == 'distance':
                    # user location should be in user model to filter search by distance
                    continue
                elif key in ['price_index', 'year_index', 'mileage_index', 'year_index']:
                    key2 = key
                    raw_filters[key] = raw_filters[key].replace(',', ' - ')

                if key2:
                    key2 = key2.replace('_', ' ').capitalize()
                    filters[key2] = raw_filters[key]
                    if key2 not in ['Brand', 'Countries']:
                        filters[key2] = filters[key2].lower()



            if not filters:
                filters['Without filters'] = 'any updates'
            result[s.id] = filters

        context['subscriptions'] = result
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['email', ]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(email=self.request.user.email)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"


class Subscribe(View):

    def post(self, request):
        category = re.match(r'^[^\/]+\/\/[^\/]+\/(\w+)', request.META['HTTP_REFERER']).groups()[0]
        if category == 'vehicles':
            category = 1
        elif category == 'realty':
            category = 2
        if request.user.is_authenticated():
            data = json.loads(request.POST['filters'])
            if 'page' in data:
                del data['page']
            if 'scroll' in data:
                del data['scroll']
            for key in ['year_index', 'mileage_index']:
                if key in data:
                    data[key] = data[key].replace('.00', '')
            Subscription.objects.get_or_create(filters=json.dumps(data),
                                               user=request.user,
                                               category=category)
            return HttpResponse(status=204)
        else:
            return HttpResponse('Not authenticated!', status=400)


class DeleteSubscriptions(LoginRequiredMixin, View):

    def post(self, request):
        ids = json.loads(request.POST['subscriptions'])
        request.user.subscription_set.filter(id__in=ids).delete()
        return HttpResponse(status=204)


def social_redirect(request):
    next_url = request.GET.get('url', ).replace('|', '?').replace('^', '&')
    if next_url:
        return redirect(to=next_url)
    return redirect(to=settings.LOGIN_REDIRECT_URL)

luxdjango/templates/users/user_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}User: {{ object.username }}{% endblock title %}

{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ object.username }}</h2>
                <h3>{{ object.email }}</h3>
                {% if object.name %}
                    <p>{{ object.name }}</p>
                {% endif %}
            </div>
        </div>

        <div>
            <h3>{% trans "Your subscriptions:" %}</h3>
            {% if subscriptions %}
                <div id="subscr-list">
                    {% for id, filters in subscriptions.iteritems %}
                        <label>
                            <input type="checkbox" name="subscr" data-id="{{ id }}">
                            {% for key, val in filters.iteritems %}
                                <span class="marg-r">{{ key }}: {{ val }};</span>
                            {% endfor %}
                        </label>
                    {% endfor %}
                    <button id="del-subscr" class="btn btn-default">{% trans "Delete selected subscriptions" %}</button>
                </div>
            {% endif %}
            <div id="no-subscr" style="{% if subscriptions %}display:none;{% endif %}">
                {% trans "No subscriptions" %}
            </div>

        </div>

        {% if object == request.user %}
        <!-- Action buttons -->
            <div class="row">
                <div class="col-sm-12 ">
                {#    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>#}
                {#    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>#}
                <!-- Your Stuff: Custom user template urls -->
                </div>
            </div>
        <!-- End Action buttons -->
        {% endif %}
    </div>
{% endblock content %}
{% block extra_js %}
    <script src="{% static "assets/base/js/modules/user-account.js" %}"></script>
{% endblock extra_js %}

luxdjango/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

luxdjango/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

{% endblock content %}