luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<email>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

realty/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailRealtyView.as_view(), name='details'),
    url(r'^add/', views.AddRealtyView.as_view(), name="add-realty"),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
]

luxdjango/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from luxdjango.users.managers import UserManager
from vehicles.models import Country


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    country = models.ForeignKey(Country, null=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Subscription(models.Model):
    CATEGORY_CHOICES = ((1, 'vehicles'), (2, 'realty'))
    user = models.ForeignKey(User)
    filters = models.CharField(max_length=500)
    last_notification = models.DateTimeField(null=True, blank=True)
    category = models.PositiveIntegerField(choices=CATEGORY_CHOICES)

realty/models.py
# -*- coding: utf-8 -*-
import datetime, hashlib, re
from django.db import models
from django.contrib.gis.geos import Point
from django.contrib.postgres.fields import ArrayField
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.utils import timezone
from django.utils.translation import ugettext as _

from vehicles.models import Country


class PropertyType(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class PropertyTypeType(models.Model):
    name = models.CharField(max_length=50)
    property_type = models.ForeignKey(PropertyType, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)
    country = models.ForeignKey(Country)

    def __unicode__(self):
        return self.name


class Seller(models.Model):
    name = models.CharField(max_length=60, null=True)

    def __unicode__(self):
        return self.name


class Realty(models.Model):
    DEAL_CHOICES = (
        (1, 'sale'),
        (2, 'rent')
    )
    ENERGY_CHOICES = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('F', 'F'),
        ('G', 'G'),
        ('H', 'H'),
        ('I', 'I'))

    property_type = models.ForeignKey(PropertyType, on_delete=models.PROTECT)  ##
    property_type_type = models.ForeignKey(
        PropertyTypeType, null=True, blank=True, on_delete=models.PROTECT
    )
    deal = models.PositiveIntegerField(choices=DEAL_CHOICES, blank=False, default=1)
    rooms = models.PositiveIntegerField(null=True, blank=True)
    area = models.PositiveIntegerField(null=True, blank=True)  # m2
    land_area = models.DecimalField(null=True, decimal_places=2, max_digits=7, blank=True)  # ares
    price = models.PositiveIntegerField(null=True, blank=True)  # euro
    price_history = ArrayField(models.IntegerField(), blank=True, null=True)
    energy_class = models.CharField(max_length=1, choices=ENERGY_CHOICES, blank=True)
    termal_protection_class = models.CharField(max_length=1, choices=ENERGY_CHOICES, blank=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)  ##
    city = models.ForeignKey(City, null=True, blank=True, on_delete=models.PROTECT)  ##
    address = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)  #
    longitude = models.FloatField(null=True, blank=True)  #
    year_built = models.PositiveIntegerField(_("Year built"), null=True, blank=True, validators=[
        MaxValueValidator(datetime.datetime.now().year), MinValueValidator(1900)
    ])
    new_building = models.NullBooleanField()
    url = models.CharField(max_length=300, null=True, blank=True)
    part_of = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)  #
    has_child = models.NullBooleanField()  #
    floor = models.PositiveIntegerField(null=True, blank=True)
    total_floors = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField(blank=True)  ##
    bathroom = models.PositiveIntegerField(_("Bathrooms"), null=True, blank=True)
    garden = models.DecimalField(null=True, decimal_places=2, max_digits=5, blank=True)
    terrace = models.PositiveIntegerField(null=True, blank=True)
    balcony = models.PositiveIntegerField(null=True, blank=True)
    garage = models.PositiveIntegerField(null=True, blank=True)
    seller = models.ForeignKey(Seller, null=True, blank=True, on_delete=models.SET_NULL)
    phones = ArrayField(
        models.CharField(max_length=24, validators=[
            RegexValidator(r'^[\s \+ 0-9]{6,17}$', 'Enter a valid phone number.')
        ]),
        null=True, blank=True
    )
    creation_date = models.DateTimeField(default=timezone.now)

    @property
    def domain(self):
        if self.url:
            domain = re.search(r'\/\/([^\/]+)', self.url)
            if domain:
                return domain.groups()[0]
        return ''

    def get_location(self):
        if self.longitude and self.latitude:
            return Point(self.longitude, self.latitude)
        else:
            return None

    def get_absolute_url(self):
        return reverse('realty:details', kwargs={'pk': self.id})

    def update_price(self, new_price):
        if self.price != new_price:
            if self.price_history:
                index = len(self.price_history) - 1
                if self.price and self.price != self.price_history[index]:
                    self.price_history.append(self.price)
                elif new_price == self.price_history[index]:
                    del self.price_history[index]
            elif self.price:
                self.price_history = [self.price]
            self.price = new_price
            self.save()


def get_hash_name(first, second, filename):
    ext = filename.split('.')[-1]
    hash_object = hashlib.md5(str(first).decode('utf-8').encode('utf-8') + \
                              str(second).encode() + \
                              str(datetime.datetime.now()).encode())
    return '{}.{}'.format(hash_object.hexdigest(), ext)


def img_upload_to(instance, filename):
    return 'car-us/%s/%s/%s' % (
        datetime.datetime.now().year, instance.realty_id,
        get_hash_name(instance.realty.address, instance.realty.property_type, filename)
    )


class RealtyImage(models.Model):
    realty = models.ForeignKey(Realty)
    image = models.ImageField(upload_to=img_upload_to)

luxdjango/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import json, re

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext as _
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View

#from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import LoginRequiredMixin
from .models import User, Subscription
from vehicles.models import Country
from realty.models import PropertyType, PropertyTypeType, City


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        subscriptions = self.request.user.subscription_set.all()
        result = {}

        for s in subscriptions:
            raw_filters = json.loads(s.filters)
            filters = {}

            if 'property_type_type' in raw_filters:
                filters['Property type'] = PropertyTypeType.objects.filter(
                    id=raw_filters['property_type_type']
                ).first().name
            elif 'property_type' in raw_filters:
                filters['Property type'] = PropertyType.objects.filter(
                    id=raw_filters['property_type']
                ).first().name
            if 'city' in raw_filters:
                filters['City'] = City.objects.get(id=raw_filters['city'])
            if 'deal' in raw_filters:
                filters[_('Deal')] = _('Sale') if raw_filters['deal'] == 1 else _('Rent')

            for key in raw_filters:
                key2 = None
                if key.endswith('_index'):
                    key2 = key.replace('_index', '')
                elif key == 'q' and raw_filters[key]:
                    key2 = 'text'
                elif key == 'countries' and raw_filters[key]:
                    key2 = key
                    country_ids = [int(x) for x in raw_filters[key].split(',')]
                    country_names = Country.objects.filter(
                        id__in=country_ids
                    ).values_list('name', flat=True)
                    raw_filters[key] = ', '.join(country_names)
                elif key == 'distance':
                    # user location should be in user model to filter search by distance
                    continue
                elif key in ['price_index', 'year_index', 'mileage_index', 'year_index']:
                    key2 = key
                    raw_filters[key] = raw_filters[key].replace(',', ' - ')

                if key2:
                    key2 = key2.replace('_', ' ').capitalize()
                    filters[key2] = raw_filters[key]
                    if key2 not in ['Brand', 'Countries']:
                        filters[key2] = filters[key2].lower()



            if not filters:
                filters['Without filters'] = 'any updates'
            result[s.id] = filters

        context['subscriptions'] = result
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):

        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['email', ]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"email": self.request.user.email})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(email=self.request.user.email)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"


class Subscribe(View):

    def post(self, request):
        category = re.match(r'^[^\/]+\/\/[^\/]+\/(\w+)', request.META['HTTP_REFERER']).groups()[0]
        if category == 'vehicles':
            category = 1
        elif category == 'realty':
            category = 2
        if request.user.is_authenticated():
            data = json.loads(request.POST['filters'])
            if 'page' in data:
                del data['page']
            if 'scroll' in data:
                del data['scroll']
            for key in ['year_index', 'mileage_index']:
                if key in data:
                    data[key] = data[key].replace('.00', '')
            Subscription.objects.get_or_create(filters=json.dumps(data),
                                               user=request.user,
                                               category=category)
            return HttpResponse(status=204)
        else:
            return HttpResponse('Not authenticated!', status=400)


class DeleteSubscriptions(LoginRequiredMixin, View):

    def post(self, request):
        ids = json.loads(request.POST['subscriptions'])
        request.user.subscription_set.filter(id__in=ids).delete()
        return HttpResponse(status=204)


def social_redirect(request):
    next_url = request.GET.get('url', ).replace('|', '?').replace('^', '&')
    if next_url:
        return redirect(to=next_url)
    return redirect(to=settings.LOGIN_REDIRECT_URL)

luxdjango/templates/realty/item_preview.html
{% load pagination_tags staticfiles i18n thumbnail %}
{% autopaginate object_list 10 %}
{% for result in object_list %}
    {% with i=result.object %}
        <div class="row c-margin-b-40">
            <div class="c-content-product-2 c-bg-white">
                <div class="col-md-4">
                    <div class="c-content-overlay">
                        <div class="c-overlay-wrapper">
                            <div class="c-overlay-content">
                                <a  class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square"
                                    href="{% url "realty:details" i.id %}">Explore</a>
                            </div>
                        </div>
                        {% thumbnail i.realtyimage_set.first.image "260x230" crop="center" as im %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height"
                                 style="height: 230px; background-image: url({{ im.url }});"></div>
                        {% empty %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height"
                                 style="height: 230px; background-size:unset;
                                        background-image: url({% static "assets/base/img/home.png"%});"></div>
                        {% endthumbnail %}
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="c-info-list">
                        <h3 class="c-title c-font-bold c-font-22 c-font-dark">
                            <a class="c-theme-link" href="{% url "realty:details" i.id %}">
                                {% if i.deal == 1 %} {% trans "Sale" %} {% else %} {% trans "Rent" %} {% endif %}
                                {% if i.property_type_type %}
                                    {{ i.property_type_type.name }}
                                {% else %}
                                    {{ i.property_type.name }}
                                {% endif %}
                            </a>
                        </h3>
                        <p class="c-desc c-font-16 c-font-thin">
                            {{ i.country.name }} {% if i.city_id %}, {{ i.city.name }} {% endif %}
                        </p>
                        {% if i.energy_class %}
                            <p class="c-desc c-font-16 c-font-thin">{% trans "Energy class" %} - {{ i.energy_class }}</p>
                        {% endif %}
                        {% if i.year_built %}
                            <p class="c-desc c-font-16 c-font-thin">{% trans "Year built" %} - {{ i.year_built }}</p>
                        {% endif %}
                        {% if i.price %}
                            <p class="c-price c-font-26 c-font-thin">{{ i.price }} &#8364;
                                {% for p in i.price_history %}
                                    <span class="c-font-26 c-font-line-through c-font-red">&#8364;{{ p }}</span>
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
{% empty %}<p>No results found.</p>{% endfor %}
{#{% paginate %}#}

luxdjango/templates/realty/left_sidebar_filters.html
{% load common %}
{% load staticfiles i18n common %}

<form name="search_form">
    <li class="c-radio-inline">
        <div class="c-radio">
            <input type="radio" class="c-radio" name="deal" id="deal-sale" value="1"
                    {% if conditions|intkey:'deal' == 1 %} checked {% endif %}>
            <label for="deal-sale">
                <span class="inc"></span>
                <span class="check"></span>
                <span class="box"></span>
                {% trans "Sale" %}
            </label>
        </div>
        <div class="c-radio">
            <input type="radio" class="c-radio" name="deal" id="deal-rent" value="2"
                    {% if conditions|intkey:'deal' == 2 %} checked {% endif %}>
            <label for="deal-rent">
                <span class="inc"></span>
                <span class="check"></span>
                <span class="box"></span>
                {% trans "Rent" %}
            </label>
        </div>
    </li>
    {% if cities %}
        <li>
            <label class="control-label c-font-uppercase c-font-bold">{% trans 'City' %}</label>
            <select id="city" class="form-control c-square c-theme">
                <option value="0">{% trans "All" %}</option>
                {% for city in cities %}
                    <option value="{{ city.id }}"
                            {% if selected_city == city.id %}selected{% endif %}>
                        {{ city.name }}
                    </option>
                {% endfor %}
            </select>
        </li>
    {% endif %}
    <li>
        <label class="control-label c-font-uppercase c-font-bold">{% trans 'Property type' %}</label>
        <select id="property_type" class="form-control c-square c-theme">
            <option value="0">{% trans "All" %}</option>
            {% for item in property_types %}
                <option value="{{ item.id }}"
                        {% if selected_pt == item.id %}selected{% endif %}>
                    {{ item.name }}
                </option>
            {% endfor %}
        </select>
    </li>
    {% for index, values in facets.items %}
        <li>
            <div style="{% if values|length >= 9 %}overflow: scroll;{% endif %} max-height: 340px; overflow-x: hidden;">
                {% for k, c in values %}
                    <div class="c-checkbox">
                        <input type="checkbox" id="{{ index }}{{ forloop.counter }}" class="c-check" name="{{ index }}"
                               value="{{ k }}"  {% if conditions|intkey:index == k %} checked {% endif %}>
                        <label for="{{ index }}{{ forloop.counter }}">
                            <span class="inc"></span>
                            <span class="check"></span>
                            <span class="box"></span>
                            {% getbykey property_tt_dict k as property_tt %}
                            <p>{{ property_tt.name }} - {{ c }}</p>
                        </label>
                    </div>
                {% endfor %}
            </div>
        </li>
    {% endfor %}
    {% if energy_class %}
        <li>
            <label class="control-label c-font-uppercase c-font-bold">{% trans 'Energy class' %}</label>
            {% for name, values in energy_class %}
                <div class="c-checkbox">
                    <input type="checkbox" id="{{ name }}{{ forloop.counter }}" class="c-check" name="energy_class"
                           value="{{ name }}"  {% if conditions|key:'energy_class' == name %} checked {% endif %}>
                    <label style="min-width: 100%" for="{{ name }}{{ forloop.counter }}">
                        <span class="inc"></span>
                        <span class="check"></span>
                        <span class="box"></span>
                        <div>
                            <span class="energy-class-name">{{ name|upper }} </span>
                            <span class="bar-wrapper">
                                <span class="bar" id="energy_class_{{ name }}"></span>
                            </span>
                            <span>{{ values }}</span>
                        </div>
                    </label>
                </div>
            {% endfor %}
        </li>
    {% endif %}
</form>

luxdjango/templates/realty/realty_search.html
{% extends "search/search_wrapper.html" %}
{% load staticfiles i18n %}

{% block sidebar_range_filters %}
    <div class="c-padding-20 c-margin-t-40 c-bg-grey-1 c-bg-img-bottom-right">
        <div class="c-content-title-1 c-margin-t-20">
            <h3 class="c-font-uppercase c-font-bold">{% trans "Year built" %}</h3>
            <div class="c-line-left"></div>
            <div id="year_index-range_slider" ></div>
            <input class="input-number" id="year_index-input-number-r">
            <input class="input-number" id="year_index-input-number-l">
        </div>
    </div>
{% endblock sidebar_range_filters %}

{% block extra_js %}
    {{ block.super }}
    <script>
        window.djangoContext.urls.ajaxSearch = "{% url 'realty:search-ajax' %}";

        document.addEventListener('DOMContentLoaded', function () {
            SearchPage({
                q_text: "{{ request.GET.q }}",
                url:"don't forget forward url namespace",
                rangeFiltersList: {
                    'price_index': [0, 3000000],
                    'year_index': [1940, new Date().getFullYear()],
                }
            });
        });
    </script>
{% endblock extra_js %}